CREATE DATABASE IF NOT EXISTS chat;
CREATE USER IF NOT EXISTS 'chat_user'@'%' IDENTIFIED BY 'chat_password';
GRANT ALL PRIVILEGES ON chat.* TO 'chat_user'@'%';
FLUSH PRIVILEGES;

USE chat;

CREATE TABLE IF NOT EXISTS messages (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP NULL DEFAULT current_timestamp(),
  PRIMARY KEY (id)
);
